name: My Second Site
favicon: null
layout_spectrum: 0.71856
typography_spectrum: 0.60408
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b70000'
    - '#ed2d00'
    - '#fe5500'
    - '#fe8f40'
    - '#1b0001'
  brandStrength: 0.4375
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
